version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app-network

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - "8000:8000"
    env_file:
      - ./gateway/.env
    environment:
      - APP_SERVICE_URL=http://app_service:8001
    networks:
      - app-network
    depends_on:
      - app_service

  app_service:
    container_name: app_service
    build:
      context: ./app_service
    ports:
      - "8001:8001"
    env_file:
      - ./app_service/.env
    environment:
      - USER_SERVICE_URL=http://user_service:8002
      - SCRAPER_SERVICE_URL=http://scraper_service:8003
    networks:
      - app-network
    depends_on:
      - user_service

  user_service:
    container_name: user_service
    build:
      context: ./user_service
    ports:
      - "8002:8002"
    env_file:
      - ./user_service/.env
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/user_service_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

  scraper_service:
    container_name: scraper_service
    build:
      context: ./scraper_service
    ports:
      - "8003:8003"
    env_file:
      - ./scraper_service/.env
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/scraper_service_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
